name: digital_namaz_watch_app
description: Digital Namaz Watch with Hijri/Shamsi, Prayer Times, Azan, Qibla - Made by Hafiz Mufti Muhammad Shoaib Khan Allai
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adhan: ^3.0.0
  hijri_date_time: ^0.1.6
  geolocator: ^10.1.0
  flutter_local_notifications: ^17.0.0
  audioplayers: ^6.0.0
  wear: ^2.0.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/azan.mp3
